[project]
name = "pdaqp"
version = "0.1.0"
description = "A multi-parametric quadratic programming solver"
readme = "README.md"
authors = [
    { name = "Daniel Arnström", email = "daniel.arnstrom@gmail.com" } 
]
requires-python = ">=3.8"
dependencies = [
    "juliacall>=0.9.23",
    "numpy",
]

[project.optional-dependencies]
plot = [
    "plotly",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
